name: Build C# EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    # 1. 指定在 LianAnBmsWin 子文件夹下执行还原
    - name: Restore dependencies
      working-directory: ./LianAnBmsWin
      run: dotnet restore

    # 2. 指定在 LianAnBmsWin 子文件夹下执行编译和单文件发布
    - name: Publish Single EXE
      working-directory: ./LianAnBmsWin
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ../publish

    # 3. 保持在外层提取生成的 exe 并上传
    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: LianAnBmsWin-EXE
        path: ./publish/*.exe
