name: Build C# EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 升级为 v5 以上版本以适配最新的 Node 24 基础环境
    - name: Checkout Code
      uses: actions/checkout@v5

    # 2. 升级为 v5 以上版本以适配最新的 Node 24 基础环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Single EXE
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish

    # 3. 升级上传组件，保证编译出的 exe 能在网页端正常下载
    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: LianAnBmsWin-EXE
        path: ./publish/*.exe
